// Generated by CoffeeScript 1.7.1
(function() {
  var AngularModuleDefinition, AngularModuleDefinitionTemplate, NullDependency,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  NullDependency = require("webpack/lib/dependencies/NullDependency");

  AngularModuleDefinitionTemplate = (function() {
    function AngularModuleDefinitionTemplate() {}

    AngularModuleDefinitionTemplate.prototype.apply = function(dep, source) {
      return source.insert(dep.range[0], "exports['" + dep.name + "'] = ");
    };

    return AngularModuleDefinitionTemplate;

  })();

  AngularModuleDefinition = (function(_super) {
    __extends(AngularModuleDefinition, _super);

    AngularModuleDefinition.Template = AngularModuleDefinitionTemplate;

    AngularModuleDefinition.prototype.type = "angular module define";

    function AngularModuleDefinition(range, name) {
      this.range = range;
      this.name = name;
      AngularModuleDefinition.__super__.constructor.apply(this, arguments);
      this.Class = AngularModuleDefinition;
    }

    return AngularModuleDefinition;

  })(NullDependency);

  module.exports = AngularModuleDefinition;

}).call(this);
