// Generated by CoffeeScript 1.7.1
(function() {
  var AngularModuleDependency, AngularModuleDependencyTemplate, ModuleDependency, WebpackMissingModule,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ModuleDependency = require("webpack/lib/dependencies/ModuleDependency");

  WebpackMissingModule = require("webpack/lib/dependencies/WebpackMissingModule");

  AngularModuleDependencyTemplate = (function() {
    function AngularModuleDependencyTemplate() {}

    AngularModuleDependencyTemplate.prototype.apply = function(dep, source, outputOptions, requestShortener) {
      var comment, content;
      if (!dep.range) {
        return;
      }
      comment = outputOptions.pathinfo ? "/*! " + requestShortener.shorten(dep.request) + " */ " : "";
      if (dep.module) {
        content = "__webpack_require__(" + comment + dep.module.id + ");\n";
      } else {
        content = WebpackMissingModule.module(dep.request);
      }
      return source.insert(0, content);
    };

    AngularModuleDependencyTemplate.prototype.applyAsTemplateArgument = function(name, dep, source) {
      if (!dep.range) {
        return;
      }
      return source.replace(dep.range[0], dep.range[1] - 1, name);
    };

    return AngularModuleDependencyTemplate;

  })();

  AngularModuleDependency = (function(_super) {
    __extends(AngularModuleDependency, _super);

    AngularModuleDependency.Template = AngularModuleDependencyTemplate;

    AngularModuleDependency.prototype.type = "angular module";

    function AngularModuleDependency(request, range) {
      this.request = request;
      this.range = range;
      AngularModuleDependency.__super__.constructor.call(this, request);
      this.Class = AngularModuleDependency;
    }

    return AngularModuleDependency;

  })(ModuleDependency);

  module.exports = AngularModuleDependency;

}).call(this);
