// Generated by CoffeeScript 1.7.1
(function() {
  var createInnerCallback;

  module.exports = createInnerCallback = function(callback, options, message) {
    var callbackWrapper, log, loggingCallbackWrapper, theLog;
    if (log = options.log) {
      theLog = [];
      loggingCallbackWrapper = function() {
        var msg, _i, _len;
        log(message);
        for (_i = 0, _len = theLog.length; _i < _len; _i++) {
          msg = theLog[_i];
          log("  " + msg);
        }
        return callback.apply(this, arguments);
      };
      loggingCallbackWrapper.log = function(msg) {
        return theLog.push(msg);
      };
      loggingCallbackWrapper.stack = options.stack;
      return loggingCallbackWrapper;
    } else if (options.stack !== callback.stack) {
      callbackWrapper = function() {
        return callback.apply(this, arguments);
      };
      callbackWrapper.stack = options.stack;
      return callbackWrapper;
    } else {
      return callback;
    }
  };

}).call(this);
